---
title: "Informe Contexto Demografico Nacional"
author: "Alejandro Brenes, Santiago Fernández, Eyeri Méndez y Erik Venegas"
date: "`r Sys.Date()`"
output: html_document
---

Se cargan las librerías necesarias.

```{r librerias}
pacman::p_load(dplyr,
               ggplot2,
               lubridate,
               readxl,
               RColorBrewer,
               tidyr)
```

## Fecundidad

Se inicia cargando los datos de la fecundidad, publicados por el INEC y juntados por cuenta propia.

```{r datos_tgf}
tgf <- read_excel("data/TGF_CR.xlsx")
colnames(tgf) <- c("anno", "tgf")
```

Se crea un gráfico de líneas, para analizar la evolución de este.

```{r grafico_tgf}
# Gráfico del TGF en Costa Rica desde 2003 hasta 2024
ggplot(tgf, aes(x = anno, y = tgf)) +
  geom_line(color = "#41AE76", linewidth = 1) +
  geom_point(color = "#238B45", size = 1.5) +
  labs(x = "Año", y = "Tasa global de fecundidad", caption = "Fuente: elaboración propia") +
  scale_x_continuous(expand = c(0, 2)) +
  theme_minimal()
```

