---
title: "Resultados"
author: "Alejandro Brenes, Santiago Fernández, Eyeri Méndez y Erick Venegas"
date: "`r Sys.Date()`"
output: html_document
---

# Preparación inicial

## Librerías

Inicialmente, cargamos las librerías necesarias para el desarrollo del modelo.

```{r librerias}
pacman::p_load(janitor,
               readxl,
               tidyverse)
```

## Datos del régimen

Se leen las bases de cotizantes y pensionados.

```{r datos_cotpen, message = FALSE, warning = FALSE}
cotizantes <- read_excel("data/BD_Cotizantes.xlsx")
pensionados <- read_excel("data/BD_Pensionados.xlsx")
```

Se realizan algunas correcciones de formato en los pensionados y en los cotizantes.

```{r correcciones_cotpen}
# Se cambian los nombres de las columnas no numéricas de los cotizantes
cotizantes <- cotizantes %>% clean_names()

# Se corrigen los nombres de las columnas de la base de cotizantes
colnames(cotizantes)[4:363] <- format(seq(
  from = ymd("1995-01-01"),
  to = ymd("2024-12-01"),
  by = "1 month"
), "%m-%Y")

# Se corrigen los nombres de la base de pensionados
pensionados <- pensionados %>% clean_names() %>% select(-c("x9"))
```

## Probabilidades de muerte

Se cargan los datos de mortalidad dinámmicos de la SUPEN.

```{r carga_mort}
#mortalidad <- read_excel("data/BD_Cotizantes.xlsx")
```

